### ISSUE TITLE
为什么测速等待时间很长

### ISSUE THREAD

**Issue by lixiaodong007** [LLM-Red-Team/glm-free-api#22]
我docker部署后，接入one-api。在one-api测速的话，每次都是15秒以上。请问为什么？

**Comment by Vinlic** [comment]
取决于测速使用的方式，如果是采取prompt响应方式久是正常的，实际体验接入流式响应体验，我们测试下来与官方速度一致。

**Comment by lixiaodong007** [comment]
`
[2024-05-10 17:55:27.581][info][index<1032,26>] -> POST /v1/chat/completions
[2024-05-10 17:55:27.581][info][index<1223,20>] [ { role: 'user', content: 'hi' } ]
[2024-05-10 17:55:27.581][info][index<1464,18>] 本次请求上传：0个文件
[2024-05-10 17:55:27.581][info][index<1141,18>] Refresh token: Authorization: Bearer eyJhbG{Refresh token}jr0pM
[2024-05-10 17:55:27.642][error][index<1276,22>] Stream response error: Error: [请求glm失败]: bad request
    at checkResult (file:///app/dist/index.js:1613:9)
    at file:///app/dist/index.js:1158:33
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async requestToken (file:///app/dist/index.js:1142:18)
    at async acquireToken (file:///app/dist/index.js:1190:14)
    at async file:///app/dist/index.js:1230:19
    at async /completions (file:///app/dist/index.js:2003:16)
[2024-05-10 17:55:27.642][warning][index<1277,22>] Try again after 5s...
[2024-05-10 17:55:32.642][info][index<1223,20>] [ { role: 'user', content: 'hi' } ]
[2024-05-10 17:55:32.642][info][index<1464,18>] 本次请求上传：0个文件
[2024-05-10 17:55:32.643][info][index<1141,18>] Refresh token: Authorization: Bearer eyJhbG{Refresh token}jr0pM
[2024-05-10 17:55:32.780][error][index<1276,22>] Stream response error: Error: [请求glm失败]: bad request
    at checkResult (file:///app/dist/index.js:1613:9)
    at file:///app/dist/index.js:1158:33
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async requestToken (file:///app/dist/index.js:1142:18)
    at async acquireToken (file:///app/dist/index.js:1190:14)
    at async file:///app/dist/index.js:1230:19
    at async /completions (file:///app/dist/index.js:2003:16)
[2024-05-10 17:55:32.780][warning][index<1277,22>] Try again after 5s...
[2024-05-10 17:55:37.780][info][index<1223,20>] [ { role: 'user', content: 'hi' } ]
[2024-05-10 17:55:37.781][info][index<1464,18>] 本次请求上传：0个文件
[2024-05-10 17:55:37.781][info][index<1141,18>] Refresh token: Authorization: Bearer eyJhbG{Refresh token}jr0pM
[2024-05-10 17:55:37.908][error][index<1276,22>] Stream response error: Error: [请求glm失败]: bad request
    at checkResult (file:///app/dist/index.js:1613:9)
    at file:///app/dist/index.js:1158:33
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async requestToken (file:///app/dist/index.js:1142:18)
    at async acquireToken (file:///app/dist/index.js:1190:14)
    at async file:///app/dist/index.js:1230:19
    at async /completions (file:///app/dist/index.js:2003:16)
[2024-05-10 17:55:37.908][warning][index<1277,22>] Try again after 5s...
[2024-05-10 17:55:42.908][info][index<1223,20>] [ { role: 'user', content: 'hi' } ]
[2024-05-10 17:55:42.908][info][index<1464,18>] 本次请求上传：0个文件
[2024-05-10 17:55:42.909][info][index<1141,18>] Refresh token: Authorization: Bearer eyJhbG{Refresh token}jr0pM
[2024-05-10 17:55:43.029][error][index<1051,28>] APIException [Error]: [请求glm失败]: bad request
    at checkResult (file:///app/dist/index.js:1613:9)
    at file:///app/dist/index.js:1158:33
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async requestToken (file:///app/dist/index.js:1142:18)
    at async acquireToken (file:///app/dist/index.js:1190:14)
    at async file:///app/dist/index.js:1230:19
    at async /completions (file:///app/dist/index.js:2003:16) {
  errcode: -2001,
  errmsg: '[请求glm失败]: bad request',
  data: undefined,
  httpStatusCode: undefined
}
[2024-05-10 17:55:43.030][info][index<1002,30>] <- POST /v1/chat/completions 15449ms`
报错如上。好像重试了三次

**Comment by Vinlic** [comment]
refresh token错误，请先检查。

**Comment by lixiaodong007** [comment]
感谢支持，已解决。one-api的秘钥那里，我填成了 Authorization: Bearer TOKEN 导致的，直接填token就可以了。非常感谢支持！
