### ISSUE TITLE
更新版本以后不可用

### ISSUE THREAD

**Issue by ssrsyds** [LLM-Red-Team/glm-free-api#44]
hi
[39m
[91m[2024-12-31 12:46:26.510][error][server.ts<121,32>] APIException [Error]: Stream response Content-Type invalid: application/json
at <anonymous> (/app/src/api/controllers/chat.ts:238:13)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
at async /completions (/app/src/api/routes/chat.ts:35:24) {
errcode: -2001,
errmsg: 'Stream response Content-Type invalid: application/json',
data: undefined,
httpStatusCode: undefined
}[39m
[96m[2024-12-31 12:46:26.511][info][server.ts<66,36>] <- POST /v1/chat/completions 15439ms[39m
[91m[2024-12-31 12:46:26.511][error][chat.ts<237,49>] {"validation_error":{"body_params":[{"loc":["assistant_id"],"msg":"field required","type":"value_error.missing"}]}}
[39m
[96m[2024-12-31 13:17:19.702][info][server.ts<99,28>] -> POST /v1/chat/completions[39m
[96m[2024-12-31 13:17:19.709][info][chat.ts<181,12>] [ { role: 'user', content: 'hi' } ][39m
[96m[2024-12-31 13:17:19.710][info][chat.ts<695,10>] 本次请求上传：0个文件[39m
[96m[2024-12-31 13:17:19.710][info][chat.ts<720,12>]
透传内容：
hi
[39m
[96m[2024-12-31 13:17:20.264][info][chat.ts<961,12>] 是否静默模型: false[39m
[32m[2024-12-31 13:17:22.861][success][chat.ts<247,12>] Stream has completed transfer 2597ms[39m
[96m[2024-12-31 13:17:22.864][info][server.ts<66,36>] <- POST /v1/chat/completions 3162ms[39m
[96m[2024-12-31 13:17:30.891][info][server.ts<99,28>] -> POST /v1/chat/completions[39m
[96m[2024-12-31 13:17:30.891][info][chat.ts<292,12>] [ { role: 'user', content: '你好' } ][39m
[96m[2024-12-31 13:17:30.892][info][chat.ts<695,10>] 本次请求上传：0个文件[39m
[96m[2024-12-31 13:17:30.892][info][chat.ts<720,12>]
透传内容：
你好
[39m
[91m[2024-12-31 13:17:31.015][error][chat.ts<349,14>] Invalid response Content-Type: application/json[39m
[96m[2024-12-31 13:17:31.016][info][server.ts<66,36>] <- POST /v1/chat/completions 125ms[39m
[91m[2024-12-31 13:17:31.017][error][chat.ts<353,49>] {"validation_error":{"body_params":[{"loc":["assistant_id"],"msg":"field required","type":"value_error.missing"}]}}
[39m

**Comment by Vinlic** [comment]
更新0.0.35

**Comment by derline** [comment]
> 更新0.0.35

也不行，报错信息带有“上传了0个文件”之类 的

**Comment by Vinlic** [comment]
需要提供完整日志
@derline

**Comment by derline** [comment]
> 需要提供完整日志 [@derline](https://github.com/derline)

[2025-01-25 06:35:21.974][warning][chat.ts<391,14>] Try again after 5s...
[2025-01-25 06:35:26.974][info][chat.ts<292,12>] [
  { role: 'user', content: '你好' },
  { role: 'assistant', content: '' },
  {
    role: 'user',
    content: 'conda create -n videolingo python=3.10.0 -y\n' +
      'conda activate videolingo\n' +
      'python install.py\n' +
      '你好'
  },
  { role: 'assistant', content: '' },
  { role: 'user', content: 'hi' }
]
[2025-01-25 06:35:26.975][info][chat.ts<695,10>] 本次请求上传：0个文件
[2025-01-25 06:35:26.975][info][chat.ts<62,10>] Refresh token: 示例tokenxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[2025-01-25 06:35:27.184][error][server.ts<121,32>] APIException [Error]: [请求glm失败]: bad request
    at checkResult (/app/src/api/controllers/chat.ts:926:9)
    at <anonymous> (/app/src/api/controllers/chat.ts:79:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async requestToken (/app/src/api/controllers/chat.ts:63:18)
    at async acquireToken (/app/src/api/controllers/chat.ts:120:14)
    at async <anonymous> (/app/src/api/controllers/chat.ts:313:19)
    at async /completions (/app/src/api/routes/chat.ts:29:32) {
  errcode: -2001,
  errmsg: '[请求glm失败]: bad request',
  data: undefined,
  httpStatusCode: undefined
}
[2025-01-25 06:35:27.185][info][server.ts<66,36>] <- POST /v1/chat/completions 16810ms

**Comment by derline** [comment]
docker logs -f glm --tail=1000

> glm-free-api@0.0.35 start
> node --enable-source-maps dist/index.js

[2025-01-25 06:34:37.239][success][server.ts<45,16>] Server initialized
[2025-01-25 06:34:37.253][info][index.ts<15,10>] <<<< glm free server >>>>
[2025-01-25 06:34:37.255][info][index.ts<16,10>] Version: 0.0.35
[2025-01-25 06:34:37.255][info][index.ts<17,10>] Process id: 18
[2025-01-25 06:34:37.256][info][index.ts<18,10>] Environment: dev
[2025-01-25 06:34:37.256][info][index.ts<19,10>] Service name: glm-free-api
[2025-01-25 06:34:37.258][info][server.ts<70,20>] Route  attached
[2025-01-25 06:34:37.260][info][server.ts<70,20>] Route /v1/chat attached
[2025-01-25 06:34:37.261][info][server.ts<70,20>] Route /v1/images attached
[2025-01-25 06:34:37.264][info][server.ts<70,20>] Route /v1/videos attached
[2025-01-25 06:34:37.265][info][server.ts<70,20>] Route /ping attached
[2025-01-25 06:34:37.266][info][server.ts<70,20>] Route /token attached
[2025-01-25 06:34:37.267][info][server.ts<70,20>] Route /v1 attached
[2025-01-25 06:34:37.275][success][server.ts<168,16>] Server listening on port 8000 (0.0.0.0)
[2025-01-25 06:34:37.275][success][index.ts<28,12>] Service startup completed (22ms)
[2025-01-25 06:35:10.375][info][server.ts<99,28>] -> POST /v1/chat/completions
[2025-01-25 06:35:10.377][info][chat.ts<292,12>] [
